import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

import { config } from "@fortawesome/free-solid-svg-icons";
import "@fortawesome/fontawesome-svg-core/styles.css";

// config.autoAddCss = false

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ticket App",
  description: "Generated by Vick",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen max-h-screen">
          <Nav />

          <div className="flex-low overflow-y-auto bg-page text-default-text h-screen">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
